require("dotenv").config();const connectDB=require("./config/db"),Artist=require("./model/Artist");
const profiles=[
 ["Elena Maris","elena-maris","Tây Ban Nha","Đương đại",["Ấn tượng","Phong cảnh"],true,"https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80","Elena Maris theo đuổi ánh sáng tự nhiên và ký ức về những miền đất yên tĩnh. Tranh của bà thường nằm giữa phong cảnh thực và cảm giác mơ hồ của hồi tưởng.","Tôi vẽ ánh sáng trước khi vẽ cảnh vật."],
 ["Marc Bell","marc-bell","Pháp","Đương đại",["Hiện đại","Trừu tượng"],true,"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80","Marc Bell sử dụng hình học và những khoảng màu đối thoại với nhau như âm thanh. Thực hành của ông khảo sát sự tĩnh lặng trong đời sống đô thị.","Một hình vuông cũng có thể mang ký ức."],
 ["Sofia Arden","sofia-arden","Ý","Đương đại",["Biểu hiện","Hoa"],true,"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80","Sofia Arden xem khu vườn như một chân dung đang biến đổi. Màu sắc mãnh liệt và nét cọ bản năng tạo nên nhịp sống đặc trưng trong tác phẩm của bà.","Mỗi khu vườn đều biết cách tự kể chuyện."],
 ["Theo Laurent","theo-laurent","Bỉ","Đương đại",["Hiện thực","Màu nước"],false,"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80","Theo Laurent ghi lại những đường chân trời lặng lẽ bằng màu nước. Sự tiết chế giúp mỗi khoảng trống trong tranh trở thành một phần của câu chuyện.","Khoảng trống là màu sắc khó dùng nhất."],
 ["Amelia Rowe","amelia-rowe","Anh","Tân cổ điển",["Cổ điển","Chân dung"],false,"https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=800&q=80","Amelia Rowe kết hợp kỹ thuật chân dung cổ điển với sự quan sát tâm lý đương đại, tập trung vào những khoảnh khắc riêng tư và trầm tư.","Một gương mặt luôn chứa nhiều hơn một thời điểm."],
 ["Jonas Vale","jonas-vale","Bồ Đào Nha","Đương đại",["Cổ điển","Tôn giáo"],false,"https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80","Jonas Vale nghiên cứu biểu tượng, ánh sáng và truyền thống hội họa tâm linh. Tác phẩm của ông đặt câu hỏi về niềm tin trong thế giới hiện đại.","Ánh sáng là biểu tượng cổ xưa nhất của hy vọng."]];
(async()=>{await connectDB();for(const [name,slug,nationality,period,styles,featured,portrait,biography,quote] of profiles)await Artist.findOneAndUpdate({name},{name,slug,nationality,period,styles,featured,portrait,biography,quote},{upsert:true,returnDocument:"after"});console.log(`Đã tạo ${profiles.length} hồ sơ nghệ sĩ.`);process.exit(0)})().catch(e=>{console.error(e);process.exit(1)});
