require("dotenv").config();const connectDB=require("./config/db"),Artist=require("./model/Artist"),Painting=require("./model/Painting"),Category=require("./model/Category");
const entries=[
 {profile:["Lucia Moretti","lucia-moretti","Ý","Đương đại",["Tối giản","Trừu tượng"],"https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80","Lucia Moretti xây dựng những không gian tĩnh bằng lớp màu mỏng và cấu trúc tối giản. Hội họa của bà tìm kiếm sự cân bằng giữa im lặng và chuyển động.","Sự im lặng cũng có hình dạng."],work:["Khoảng lặng màu son","Trừu tượng","Tối giản","Acrylic","Vải toan","Những mảng màu son và kem gặp nhau trong một bố cục tiết chế về ký ức.","https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1000&q=85"]},
 {profile:["Haruto Seki","haruto-seki","Nhật Bản","Đương đại",["Màu nước","Thiên nhiên"],"https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=800&q=80","Haruto Seki quan sát thiên nhiên qua những biến đổi mong manh của mùa và thời tiết. Ông để nước, giấy và sắc độ cùng tham gia vào quá trình sáng tác.","Nước luôn biết con đường của riêng mình."],work:["Sương qua rừng trúc","Thiên nhiên","Màu nước","Màu nước","Giấy","Một khoảnh khắc sương sớm trôi qua rừng trúc, nhẹ và gần như không trọng lượng.","https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=1000&q=85"]},
 {profile:["Nora Ibrahim","nora-ibrahim","Ai Cập","Đương đại",["Hình tượng","Biểu hiện"],"https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=800&q=80","Nora Ibrahim kết hợp ký ức gia đình, hoa văn và hình thể con người. Tác phẩm của bà nói về căn tính, sự dịch chuyển và cảm giác thuộc về.","Cơ thể là kho lưu trữ đầu tiên của chúng ta."],work:["Người mang ký ức","Chân dung","Biểu hiện","Sơn dầu","Vải toan","Hình thể và hoa văn xếp lớp thành một chân dung về căn tính và ký ức di truyền.","https://images.unsplash.com/photo-1551913902-c92207136625?auto=format&fit=crop&w=1000&q=85"]},
 {profile:["Gabriel Chen","gabriel-chen","Singapore","Đương đại",["Hiện đại","Đô thị"],"https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80","Gabriel Chen ghi lại những nhịp điệu kiến trúc của thành phố châu Á. Các lớp hình học và ánh sáng trong tranh gợi nên cảm giác vừa quen thuộc vừa vô danh.","Thành phố là bức chân dung được vẽ bởi đám đông."],work:["Thành phố lúc 5:47","Phong cảnh","Hiện đại","Acrylic","Vải toan","Các khối kiến trúc và ánh chiều va vào nhau trong nhịp sống đô thị đang chuyển động.","https://images.unsplash.com/photo-1547891654-e66ed7ebb968?auto=format&fit=crop&w=1000&q=85"]},
 {profile:["Claire Dubois","claire-dubois","Pháp","Đương đại",["Ấn tượng","Hoa"],"https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80","Claire Dubois tiếp nối tinh thần ấn tượng bằng một bảng màu đương đại. Bà quan tâm đến những khoảnh khắc màu sắc thay đổi trước khi hình ảnh kịp ổn định.","Màu sắc đến trước tên gọi của sự vật."],work:["Mùa hoa tháng Tư","Hoa","Ấn tượng","Sơn dầu","Vải toan","Một khu vườn tháng Tư tan vào ánh sáng qua những nét cọ mềm và bảng màu trong trẻo.","https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1000&q=85"]},
 {profile:["Mateo Silva","mateo-silva","Brazil","Đương đại",["Trừu tượng","Biểu hiện"],"https://images.unsplash.com/photo-1507591064344-4c6ce005b128?auto=format&fit=crop&w=800&q=80","Mateo Silva đưa nhịp điệu âm nhạc và năng lượng đường phố vào hội họa. Bề mặt tranh của ông dày, nhiều lớp và luôn có cảm giác đang tiếp tục chuyển động.","Một bức tranh tốt phải còn nhịp tim."],work:["Nhịp đỏ nhiệt đới","Trừu tượng","Biểu hiện","Acrylic","Gỗ","Màu đỏ, xanh thẫm và vàng va chạm như một bản nhạc không lời giàu năng lượng.","https://images.unsplash.com/photo-1577083552431-6e5fd01988a5?auto=format&fit=crop&w=1000&q=85"]}
];
(async()=>{await connectDB();for(const entry of entries){const [name,slug,nationality,period,styles,portrait,biography,quote]=entry.profile;await Artist.findOneAndUpdate({name},{name,slug,nationality,period,styles,portrait,biography,quote,featured:false},{upsert:true,returnDocument:"after"});const [title,categoryName,style,colorMedium,surfaceMaterial,description,url]=entry.work,category=await Category.findOne({name:categoryName});if(!category)throw new Error(`Thiếu danh mục ${categoryName}`);await Painting.findOneAndUpdate({title},{title,artist:name,category:category._id,style,colorMedium,surfaceMaterial,description,aiSummary:`Một tác phẩm ${style.toLowerCase()} nổi bật bởi nhịp điệu thị giác và cách tổ chức màu sắc riêng của ${name}.`,tags:[categoryName.toLowerCase(),style.toLowerCase(),colorMedium.toLowerCase()],embeddingTags:[categoryName,style,colorMedium],images:[{url,isPrimary:true}],popularityScore:15+Math.floor(Math.random()*25),isAvailable:true},{upsert:true,returnDocument:"after",runValidators:true})}console.log(`Đã bổ sung ${entries.length} nghệ sĩ và tác phẩm.`);process.exit(0)})().catch(e=>{console.error(e);process.exit(1)});
