require("dotenv").config();
const bcrypt=require("bcrypt"),connectDB=require("./config/db"),Category=require("./model/Category"),Painting=require("./model/Painting"),User=require("./model/User");
const categoryPairs=[["Abstract","Trừu tượng"],["Landscape","Phong cảnh"],["Flower","Hoa"],["Nature","Thiên nhiên"],["Figurative","Chân dung"],["Religious","Tôn giáo"]];
const works=[
 ["Whispers of the Valley","Lời thì thầm của thung lũng","Elena Maris","Phong cảnh","Ấn tượng","Sơn dầu","Vải toan","Một thung lũng yên bình hiện lên qua ánh sáng ấm áp và những lớp cọ giàu cảm xúc.","https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=1000&q=85"],
 ["Blue Interior","Khoảng xanh nội tâm","Marc Bell","Trừu tượng","Hiện đại","Acrylic","Vải toan","Chuyển động hình học khám phá sự tĩnh lặng qua sắc xanh và màu đất son.","https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1000&q=85"],
 ["Wild Garden","Khu vườn hoang dã","Sofia Arden","Hoa","Biểu hiện","Sơn dầu","Vải toan","Một nghiên cứu tràn đầy năng lượng về hoa, màu sắc và sức sống tự do.","https://images.unsplash.com/photo-1577083552431-6e5fd01988a5?auto=format&fit=crop&w=1000&q=85"],
 ["Silent Coast","Bờ biển tĩnh lặng","Theo Laurent","Thiên nhiên","Hiện thực","Màu nước","Giấy","Biển và trời gặp nhau trong một suy tưởng nhẹ nhàng về khoảng cách.","https://images.unsplash.com/photo-1578301978018-3005759f48f7?auto=format&fit=crop&w=1000&q=85"],
 ["The Reader","Người đọc sách","Amelia Rowe","Chân dung","Cổ điển","Sơn dầu","Gỗ","Một chân dung trầm tư được định hình bởi nguồn sáng tự nhiên dịu nhẹ.","https://images.unsplash.com/photo-1579783928621-7a13d66a62d1?auto=format&fit=crop&w=1000&q=85"],
 ["Sacred Light","Ánh sáng thiêng liêng","Jonas Vale","Tôn giáo","Cổ điển","Sơn dầu","Vải toan","Ánh sáng trở thành biểu tượng của niềm hy vọng trong bố cục giàu tính chiêm nghiệm.","https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=1000&q=85"]
];
(async()=>{await connectDB();const cats={};for(const [oldName,name] of categoryPairs)cats[name]=await Category.findOneAndUpdate({name:{$in:[oldName,name]}},{name,description:`Tuyển chọn những tác phẩm thuộc chủ đề ${name.toLowerCase()}`},{upsert:true,returnDocument:"after"});for(const [oldTitle,title,artist,cat,style,medium,surface,description,url] of works)await Painting.findOneAndUpdate({title:{$in:[oldTitle,title]}},{title,artist,category:cats[cat]._id,style,colorMedium:medium,surfaceMaterial:surface,description,aiSummary:`Một tác phẩm mang phong cách ${style.toLowerCase()}, nổi bật bởi nhịp điệu thị giác, bầu không khí và bảng màu giàu biểu cảm.`,tags:[cat.toLowerCase(),style.toLowerCase(),medium.toLowerCase()],embeddingTags:[cat,style,medium],images:[{url,isPrimary:true}],popularityScore:Math.floor(Math.random()*40)+10},{upsert:true,returnDocument:"after",runValidators:true});const email=process.env.ADMIN_EMAIL||"admin@artelier.local",password=process.env.ADMIN_PASSWORD||"Admin123!";await User.findOneAndUpdate({email},{name:"Quản trị Artelier",email,password:await bcrypt.hash(password,12),role:"admin",isActive:true},{upsert:true,returnDocument:"after"});console.log(`Đã tạo dữ liệu tiếng Việt. Tài khoản quản trị: ${email}`);process.exit(0)})().catch(e=>{console.error(e);process.exit(1)});
